name: "CD - Runner - Dev ツ"

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest # construye y prueba un proyecto de gradle en un entorno de ubuntu
    name: Build project

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2 #action para configurar gradle en el entorno de ejecución

      - name: Build project
        env:
          GITHUB_ACTOR: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH_SERVER_URI: ${{ secrets.AUTH_SERVER_URI }}
          AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
          AUTH_CLIENT_SECRET: ${{ secrets.AUTH_CLIENT_SECRET }}
        run: ./gradlew build

  build-and-publish:
    runs-on: ubuntu-latest
    name: Image build and publish
    needs: build

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.ACTOR }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/ingsis-group10-2024/snippet-runner-dev:latest
          build-args: |
            GITHUB_ACTOR=${{ github.repository_owner }}
            GITHUB_TOKEN=${{ secrets.TOKEN }} 
            AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}
            AUTH_SERVER_URI=${{ secrets.AUTH_SERVER_URI }}
            AUTH_CLIENT_ID=${{ secrets.AUTH_CLIENT_ID }}
            AUTH_CLIENT_SECRET=${{ secrets.AUTH_CLIENT_SECRET }}

  deploy:
    name: Runner deployment
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
      - name: Update and Restart Runner Infrastructure
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_URL }}
          username: "mcchicken"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd snippet-infra 
            sudo su
            docker container stop snippet-runner  
            docker container rm snippet-runner  
            docker-compose -f docker-compose.yml pull runner  
            docker-compose -f docker-compose.yml up -d runner  
            docker image prune -f